/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as ScrapedSchemesRouteImport } from './routes/scraped-schemes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FeaturedSchemesRouteImport } from './routes/featured-schemes'
import { Route as DocumentScannerRouteImport } from './routes/document-scanner'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BenefitsRouteImport } from './routes/benefits'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchemeIdRouteImport } from './routes/scheme.$id'
import { Route as BenefitsCategoryRouteImport } from './routes/benefits.$category'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapedSchemesRoute = ScrapedSchemesRouteImport.update({
  id: '/scraped-schemes',
  path: '/scraped-schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedSchemesRoute = FeaturedSchemesRouteImport.update({
  id: '/featured-schemes',
  path: '/featured-schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentScannerRoute = DocumentScannerRouteImport.update({
  id: '/document-scanner',
  path: '/document-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsRoute = BenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemeIdRoute = SchemeIdRouteImport.update({
  id: '/scheme/$id',
  path: '/scheme/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsCategoryRoute = BenefitsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => BenefitsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/benefits': typeof BenefitsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/document-scanner': typeof DocumentScannerRoute
  '/featured-schemes': typeof FeaturedSchemesRoute
  '/profile': typeof ProfileRoute
  '/scraped-schemes': typeof ScrapedSchemesRoute
  '/upgrade': typeof UpgradeRoute
  '/benefits/$category': typeof BenefitsCategoryRoute
  '/scheme/$id': typeof SchemeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/benefits': typeof BenefitsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/document-scanner': typeof DocumentScannerRoute
  '/featured-schemes': typeof FeaturedSchemesRoute
  '/profile': typeof ProfileRoute
  '/scraped-schemes': typeof ScrapedSchemesRoute
  '/upgrade': typeof UpgradeRoute
  '/benefits/$category': typeof BenefitsCategoryRoute
  '/scheme/$id': typeof SchemeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/benefits': typeof BenefitsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/document-scanner': typeof DocumentScannerRoute
  '/featured-schemes': typeof FeaturedSchemesRoute
  '/profile': typeof ProfileRoute
  '/scraped-schemes': typeof ScrapedSchemesRoute
  '/upgrade': typeof UpgradeRoute
  '/benefits/$category': typeof BenefitsCategoryRoute
  '/scheme/$id': typeof SchemeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/benefits'
    | '/dashboard'
    | '/document-scanner'
    | '/featured-schemes'
    | '/profile'
    | '/scraped-schemes'
    | '/upgrade'
    | '/benefits/$category'
    | '/scheme/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/benefits'
    | '/dashboard'
    | '/document-scanner'
    | '/featured-schemes'
    | '/profile'
    | '/scraped-schemes'
    | '/upgrade'
    | '/benefits/$category'
    | '/scheme/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/benefits'
    | '/dashboard'
    | '/document-scanner'
    | '/featured-schemes'
    | '/profile'
    | '/scraped-schemes'
    | '/upgrade'
    | '/benefits/$category'
    | '/scheme/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BenefitsRoute: typeof BenefitsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DocumentScannerRoute: typeof DocumentScannerRoute
  FeaturedSchemesRoute: typeof FeaturedSchemesRoute
  ProfileRoute: typeof ProfileRoute
  ScrapedSchemesRoute: typeof ScrapedSchemesRoute
  UpgradeRoute: typeof UpgradeRoute
  SchemeIdRoute: typeof SchemeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scraped-schemes': {
      id: '/scraped-schemes'
      path: '/scraped-schemes'
      fullPath: '/scraped-schemes'
      preLoaderRoute: typeof ScrapedSchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured-schemes': {
      id: '/featured-schemes'
      path: '/featured-schemes'
      fullPath: '/featured-schemes'
      preLoaderRoute: typeof FeaturedSchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-scanner': {
      id: '/document-scanner'
      path: '/document-scanner'
      fullPath: '/document-scanner'
      preLoaderRoute: typeof DocumentScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits': {
      id: '/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof BenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheme/$id': {
      id: '/scheme/$id'
      path: '/scheme/$id'
      fullPath: '/scheme/$id'
      preLoaderRoute: typeof SchemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits/$category': {
      id: '/benefits/$category'
      path: '/$category'
      fullPath: '/benefits/$category'
      preLoaderRoute: typeof BenefitsCategoryRouteImport
      parentRoute: typeof BenefitsRoute
    }
  }
}

interface BenefitsRouteChildren {
  BenefitsCategoryRoute: typeof BenefitsCategoryRoute
}

const BenefitsRouteChildren: BenefitsRouteChildren = {
  BenefitsCategoryRoute: BenefitsCategoryRoute,
}

const BenefitsRouteWithChildren = BenefitsRoute._addFileChildren(
  BenefitsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BenefitsRoute: BenefitsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DocumentScannerRoute: DocumentScannerRoute,
  FeaturedSchemesRoute: FeaturedSchemesRoute,
  ProfileRoute: ProfileRoute,
  ScrapedSchemesRoute: ScrapedSchemesRoute,
  UpgradeRoute: UpgradeRoute,
  SchemeIdRoute: SchemeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
